added colors in style-guide
ipice1618/W01CH05 pull request #4
Opened 2021-10-01 17:59 UTC by ipice1618

2021-10-01 18:01 UTC, xavier-tadeo submitted a review, later dismissed
Perfecta!

2021-10-02 06:54 UTC, mariogl requested changes
¡Muy bien por usar SASS! He anotado cosillas en algunas líneas para que le echéis un ojo (@ipice1618 , coméntalas con el equipo).

2021-10-02 06:54 UTC, mariogl commented on .gitignore
> -.prettierignore
Os está faltando una línea en blanco al final del archivo. Esto es seguramente porque no creasteis el .editorconfig antes que cualquier otro archivo. Si es por esto, sólo tenéis que abrir el .gitignore y guardarlo. Se debería añadir el salto de línea automáticamente.

2021-10-02 06:54 UTC, mariogl commented on index.html
> +          class="main-section__dibu-tarta">
Recordad no usar abreviaturas como _dibu_ y no mezclar idiomas. O clases en inglés o clases en castellano.

2021-10-02 06:54 UTC, mariogl commented on index.html
> +        <div class="main-section__widget main-section__widget--1">
Recordad no usar ordinales en los nombres de las clases. Esos elementos mañana podrían estar en otro orden. En los nombres de las clases debemos poner cosas que aludan a qué es el elemento, qué función cumple, etc... Pensad en qué diferencia al widget 1 del 2 más allá de su posición (si es sólo la posición, les dais estilo con las pseudoclases que sirven para ello).

2021-10-02 06:54 UTC, mariogl commented on style.scss
> +.main-section__dibu-tarta {
Ya que estáis usando SASS, deberíais anidar los selectores. El selector .main-section__dibu-tarta debería estar anidado dentro del .main-section que tenéis más arriba.

2021-10-02 06:58 UTC, mariogl commented
Importante @ipice1618 @xavier-tadeo y @AipMichael : las ramas hay que borrarlas en cuanto se cierran las PR correspondientes.

2021-10-02 09:33 UTC, AipMichael approved these changes
OK.
Pendiente revisión final de BEM, Sass y propiedades DRY, etc.

2021-10-02 09:34 UTC, merged